import io
import time
import logging
from app.agents.state import AgentState
from app.agents.llm import get_model, extract_text_content
from app.core.storage import upload_file_artifact
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

logger = logging.getLogger("cortexflow")

PDF_PROMPT = """Create a comprehensive, professional document about the following topic:
Topic: {topic}

Output Structure:
- Title on the first line
- Professional Summary / Introduction
- 3 to 5 detailed sub-sections with clear headings and key bullet points
- Conclusion and action items

Rules:
- Plain text only with standard headings. Do NOT include markdown stars (**), hashes (###), or code blocks.
"""

async def pdf_gen_node(state: AgentState) -> AgentState:
    prompt = state.get("prompt", "")
    llm = get_model("pdf")

    try:
        response = await llm.ainvoke(PDF_PROMPT.format(topic=prompt))
        raw_text = extract_text_content(response.content).strip()

        # Build PDF using ReportLab
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=14
        )
        heading_style = ParagraphStyle(
            'DocHeading',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#2563EB'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'DocBody',
            parent=styles['Normal'],
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )

        elements = []
        lines = [line.strip() for line in raw_text.split("\n") if line.strip()]
        doc_title = lines[0] if lines else "CortexFlow AI Report"

        elements.append(Paragraph(doc_title, title_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563EB'), spaceAfter=14))

        for line in lines[1:]:
            if len(line) < 60 and not line.endswith(".") and (line.isupper() or line.endswith(":") or not line.startswith("-")):
                elements.append(Paragraph(line, heading_style))
            else:
                elements.append(Paragraph(line, body_style))

        elements.append(Spacer(1, 15))
        elements.append(Paragraph("Generated by CortexFlow AI Platform", ParagraphStyle('Footer', parent=styles['Italic'], fontSize=9, textColor=colors.HexColor('#94A3B8'))))

        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        filename = f"report_{int(time.time())}.pdf"
        download_url = await upload_file_artifact(pdf_bytes, filename, "application/pdf")

        return {
            **state,
            "response": f"""# 📄 Document Generated Successfully\n\n**Title:** {doc_title}\n\n📥 **[Download PDF Document]({download_url})**\n\n*(File is ready for viewing and download)*""",
            "agent": "pdf"
        }
    except Exception as e:
        logger.error(f"PDF Gen Agent error: {e}")
        return {
            **state,
            "response": f"Failed to generate PDF document: {str(e)}",
            "agent": "pdf"
        }
